# Generated by Django 3.1.4 on 2021-12-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_blog_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_cat',
            field=models.ManyToManyField(blank=True, null=True, to='blog_app.blog_category'),
        ),
    ]
