# Generated by Django 3.1.4 on 2021-12-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_blog_blog_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=40, null=True)),
                ('comment_email', models.EmailField(max_length=20, null=True)),
            ],
        ),
    ]
