# Generated by Django 3.1.4 on 2021-12-15 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_blog_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_comm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.blog_comment'),
        ),
        migrations.AlterField(
            model_name='blog_category',
            name='category_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
