# Generated by Django 3.1.4 on 2021-12-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_auto_20211216_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_category',
            name='category_name',
            field=models.CharField(default='Null category Name', max_length=20),
        ),
    ]
