# Generated by Django 3.1.4 on 2021-12-16 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_auto_20211216_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_comm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog_app.blog_comment'),
        ),
    ]
