# Generated by Django 3.1.4 on 2021-12-16 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(blank=True, max_length=40, null=True)),
                ('blog_content', models.CharField(blank=True, max_length=10000, null=True)),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='Null category Name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Blog_cat_relate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.blog')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.category')),
            ],
            options={
                'unique_together': {('blog', 'category')},
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_cat',
            field=models.ManyToManyField(through='blog_app.Blog_cat_relate', to='blog_app.Category'),
        ),
    ]
