# Generated by Django 3.1.4 on 2021-12-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20211216_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_cat',
        ),
    ]
