# Generated by Django 3.1.4 on 2021-12-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_blog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_comment',
            name='comment_email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
